# Generated by Django 4.2 on 2023-06-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_author_delete_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
